import { GeistSans } from "geist/font/sans";

import "./globals.css";

export const metadata = {
  title: "Car Land",
  description: "Generated by create next app",
};

// search context provider
import { SearchContextProvider } from "./context/search";

export default function RootLayout({ children }) {
  return (
    <SearchContextProvider>
      <html lang="en" className={GeistSans.className}>
        <body>{children}</body>
      </html>
    </SearchContextProvider>
  );
}
